print('====== DESAFIO 04 ======')

n1 = input('Digite algo: ')
print('é alpha numerico? ')
print(n1.isnumeric())
print(n1.isupper())
print(n1.islower())
print(n1.isalpha())
print(n1.isalnum())
print(n1.isspace())
print(n1.isdecimal())
print(n1.isidentifier())
print(n1.isdigit)
print(n1.isascii)
print(n1.isprintable)
print(n1.isspace)
print(type(n1))